### ISSUE TITLE
Facing issue while installing Dynamic on MAC

### ISSUE THREAD

**Issue by gourav-bhnetwork** [IndianOpenSourceFoundation/dynamic-cli#119]
Hey,

I installed dynamic cli on my local. I'm facing issue - 

```
➜  ~ dynamic -s        
Traceback (most recent call last):
  File "/Users/gsard00/.pyenv/versions/cc362/bin/dynamic", line 11, in <module>
    load_entry_point('dynamic', 'console_scripts', 'dynamic')()
  File "/Users/gsard00/.pyenv/versions/3.6.2/envs/cc362/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/gsard00/.pyenv/versions/3.6.2/envs/cc362/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Users/gsard00/.pyenv/versions/3.6.2/envs/cc362/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/gsard00/.pyenv/versions/3.6.2/envs/cc362/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/gsard00/Desktop/dynamic-cli/main.py", line 4, in <module>
    from src.arguments.search import Search
  File "/Users/gsard00/Desktop/dynamic-cli/src/arguments/search.py", line 7, in <module>
    from .utility import Utility
  File "/Users/gsard00/Desktop/dynamic-cli/src/arguments/utility.py", line 12, in <module>
    from simple_term_menu import TerminalMenu
  File "/Users/gsard00/.pyenv/versions/3.6.2/envs/cc362/lib/python3.6/site-packages/simple_term_menu.py", line 118, in <module>
    class BoxDrawingCharacters:
  File "/Users/gsard00/.pyenv/versions/3.6.2/envs/cc362/lib/python3.6/site-packages/simple_term_menu.py", line 119, in BoxDrawingCharacters
    if getlocale()[1] == "UTF-8":
  File "/Users/gsard00/.pyenv/versions/3.6.2/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/Users/gsard00/.pyenv/versions/3.6.2/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

To solve this, You'll have to follow below instructions in bashrc or zshrc depend upon your mac.

1. Open bashrc/zshrc and copy paste below line
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
2. run source ~/.bash_profile

Now issue will be resolved. Link [here](https://stackoverflow.com/questions/38916461/valueerror-unknown-locale-utf-8-when-importing-pandas-in-python-2-7)

**Comment by GouravSardana** [comment]
Hey everyone,

This is me only trying dynamic on mac. So i face this issue.

Can somebody add this in the read me?

**Comment by GouravSardana** [comment]
Can someone add this in Readme under mac guidelines ?

**Comment by GouravSardana** [comment]
added in the doc already. Closing
